dist: xenial
git:
  depth: 1
sudo: required
services:
  - docker

before_install:
  - docker pull tobiasherzke/docker-jenkins-buildenv:mha_x86_64-linux-gcc-7
language: cpp
script:
  - docker run -v $PWD:/workspace tobiasherzke/docker-jenkins-buildenv:mha_x86_64-linux-gcc-5 make -C /workspace test unit-tests deb
