os: osx
addons:
  homebrew:
    packages:
      - libsndfile
      - pkgconfig
      - portaudio
      - liblo
      - octave
      - jack
# dist: xenial
git:
  depth: 1
sudo: required
#services:
#  - docker

#before_install:
#  - docker pull tobiasherzke/docker-jenkins-buildenv:mha_x86_64-linux-gcc-7
language: cpp
script:
  - brew install libsndfile pkgconfig liblo octave jack; brew ls --verbose libsndfile; ls -l /usr/include /usr/local/include; make test unit-tests pkg
