os: osx
osx_image: xcode10.1
addons:
  homebrew:
    packages:
      - libsndfile
      - pkgconfig
      - portaudio
      - liblo
      - octave
      - jack
    update: true
    taps: AdoptOpenJDK/openjdk
    casks: adoptopenjdk11
    
git:
  depth: 1
sudo: required

language: cpp
script:
  - sudo ln -s adoptopenjdk-11.jdk/ /Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk
  - echo PATH=$PATH
  - mkdir -p /Users/travis/bin/
  - g++ -std=gnu++11 -o /Users/travis/bin/g++ mha/tools/g++.cpp
  - ls -l /Users/travis/bin/
  - octave --no-gui --no-window-system --eval "pkg install -forge -verbose control signal"
  - rm /Users/travis/bin/g++
  - make test unit-tests pkg
