os: osx
osx_image: xcode10.1
addons:
  homebrew:
    packages:
      - libsndfile
      - pkgconfig
      - portaudio
      - liblo
      - octave
      - jack
# dist: xenial
git:
  depth: 1
sudo: required
#services:
#  - docker

#before_install:
#  - docker pull tobiasherzke/docker-jenkins-buildenv:mha_x86_64-linux-gcc-7
language: cpp
script:
  - ls -lR /Library/Java/JavaVirtualMachines/; brew install libsndfile pkgconfig liblo octave jack; brew tap AdoptOpenJDK/openjdk; brew search /adoptopenjdk/; brew cask install adoptopenjdk11; ls -lR /Library/Java/JavaVirtualMachines/; make test unit-tests pkg
