os: osx
addons:
  homebrew:
    packages:
      - libsndfile
      - pkgconfig
      - portaudio
      - liblo
      - octave
# dist: xenial
git:
  depth: 1
sudo: required
#services:
#  - docker

#before_install:
#  - docker pull tobiasherzke/docker-jenkins-buildenv:mha_x86_64-linux-gcc-7
language: cpp
script:
  - make -C /workspace test unit-tests pkg
